### ISSUE TITLE
How to specify all regions for command 'fast5mod call', why default is chr1?

### ISSUE THREAD

**Issue by liuyang2006** [nanoporetech/fast5mod#11]
Hi,

We found in the command help, the --region default is None. However, when we run the followings, we found the program parsing --region by default using chr1.  Can you help us to figure out how to specify all regions? We also got exceptions below. Thank you for your help!

`fast5mod call --meth cpg meth_5.bam hg38.fasta meth_5.tsv`

```
[19:08:17 - Mextract] Processing meth_5.bam.
[19:08:17 - Mextract] Calling methylation at cpg sites.
[E::idx_find_and_load] Could not retrieve index file for 'meth_5.bam'
[E::idx_find_and_load] Could not retrieve index file for 'meth_5.bam'
[19:08:17 - Mextract] Processing region: chr1:0-248956422.
[19:08:19 - Mextract] Searching for motif 'CG'.
Traceback (most recent call last):
  File "/home/liuya/anaconda3/envs/nanocompare/bin/fast5mod", line 8, in <module>
    sys.exit(main())
  File "/home/liuya/anaconda3/envs/nanocompare/lib/python3.6/site-packages/fast5mod/fast5mod.py", line 107, in main
    args.func(args)
  File "/home/liuya/anaconda3/envs/nanocompare/lib/python3.6/site-packages/fast5mod/programs.py", line 481, in call_methylation
    region.ref_name, region.start, region.end)
  File "pysam/libcalignmentfile.pyx", line 1331, in pysam.libcalignmentfile.AlignmentFile.pileup
ValueError: no index available for pileup
```

**Comment by cjw85** [comment]
If no region argument is specified, or regions contained within the bam file will be process.

The issue here appears to be that your bam file has not been indexed with `samtools index`.
