### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'view'` in guppy2sam

### ISSUE THREAD

**Issue by yyoshiaki** [nanoporetech/fast5mod#2]
Hi @cjw85, 

Thank you for the quick response (https://github.com/nanoporetech/medaka/issues/187). I got a similar (but different?) error in fast5mod v1.0.0.
Here are guppy(Version 3.6.1+249406c) and fast5mod commands.

```
guppy_basecaller -c dna_r9.4.1_450bps_hac.cfg --fast5_out  --compress_fastq -i fast5_pass/ -s basecalled/ --device "cuda:0 cuda:1 "
fast5mod guppy2sam basecalled \
--reference reference.fasta \
--recursive > meth2.bam
```

and this is the error

```
...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callba
cks
    callback(self)
  File "/home/yyasumizu/.local/lib/python3.6/site-packages/fast5mod/programs.py", line 256, in _store
    sys.stderr.write(e)
TypeError: write() argument must be str, not KeyError
[08:44:59 - concurrent.futures] exception calling callback for <Future at 0x2ac80e0ab710 state=finished r
aised KeyError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_wor
ker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/yyasumizu/.local/lib/python3.6/site-packages/fast5mod/programs.py", line 132, in hdf_to_sam
_worker
    'Analyses/{}/{}'.format(latest, MODBASEPATH)]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/yyasumizu/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem_
_
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'ModBaseProbs' doesn't exist)"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yyasumizu/.local/lib/python3.6/site-packages/fast5mod/programs.py", line 252, in _store
    results = future.result()
  File "/home/yyasumizu/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/yyasumizu/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
KeyError: "Unable to open object (object 'ModBaseProbs' doesn't exist)"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callba
cks
    callback(self)
  File "/home/yyasumizu/.local/lib/python3.6/site-packages/fast5mod/programs.py", line 256, in _store
    sys.stderr.write(e)
TypeError: write() argument must be str, not KeyError
```

Do you have any idea?
best, Yoshiaki

**Comment by cjw85** [comment]
This part of the error:

    Unable to open object (object 'ModBaseProbs' doesn't exist)

Looks like your input files have not been created using a methylation aware basecaller model in Guppy. I dont recall the name of this off the top of my head but it's reasonably obvious which model to use if you list all the models in Guppy.

**Comment by yyoshiaki** [comment]
Thank you! `dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac_prom.cfg ` worked well!
