### ISSUE TITLE
TypeError: write() argument must be str, not BrokenProcessPool

### ISSUE THREAD

**Issue by replikation** [nanoporetech/fast5mod#3]
* the previously described error (see [#190](https://github.com/nanoporetech/medaka/issues/190)) persits
* just replaced the medaka with fast5mod, same environment, machine etc.
* here is the output with fast5mod

````bash
[11:24:59 - ModExtract] NOTE: Mod. base scores are output w.r.t the sequencing direction, not the aligned read orientation.
[11:24:59 - Extractor] Starting worker processes.
[11:24:59 - Extractor] Found 2 files to process.
[11:24:59 - ModExtract] Processing basecalling_results/workspace/FAK43478_25ade4b28ed49f8064ebcae8fc04f95ce85bb3aa_0.fast5.
[11:24:59 - ModExtract] Processing basecalling_results/workspace/FAK43478_25ade4b28ed49f8064ebcae8fc04f95ce85bb3aa_1.fast5.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
[11:29:22 - concurrent.futures] exception calling callback for <Future at 0x7fb2e025cf98 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fast5mod/programs.py", line 252, in _store
    results = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.6/dist-packages/fast5mod/programs.py", line 256, in _store
    sys.stderr.write(e)
TypeError: write() argument must be str, not BrokenProcessPool
[11:29:22 - concurrent.futures] exception calling callback for <Future at 0x7fb2e0269978 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fast5mod/programs.py", line 252, in _store
    results = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.6/dist-packages/fast5mod/programs.py", line 256, in _store
    sys.stderr.write(e)
TypeError: write() argument must be str, not BrokenProcessPool
````

**Comment by cjw85** [comment]
@replikation,

Could you provide one of the fast5 files you are attempting to input into fast5mod?

**Comment by replikation** [comment]
* sorry for the late answer, the file is available here: http://gofile.me/3DdYC/Zkg5sMYpv
