### ISSUE TITLE
Creating read_id as column from modified base call (guppy) output

### ISSUE THREAD

**Issue by JayVaz18** [nanoporetech/fast5mod#9]
Hello,

I recently used guppy to find modified base calls and that resulted in a fast5 file. After running this command: 

```
from ont_fast5_api.fast5_interface import get_fast5_file
with get_fast5_file(fast5_filepath, mode="r") as f5:
for read_id in f5.get_read_ids():
read = f5.get_read(read_id)
latest_basecall = read.get_latest_analysis('Basecall_1D')
mod_base_table = read.get_analysis_dataset(
latest_basecall, 'BaseCalled_template/ModBaseProbs')

table_path = '{}/BaseCalled_template/ModBaseProbs'.format(latest_basecall)
metadata = read.get_analysis_attributes(table_path)
print(read_id, metadata['modified_base_long_names'])
print(read_id, mod_base_table)

```

With this, I'm able to run the print(read_id, mod_base_table) to see for each read, the probability of each base being modified. However, I would like to pass this to a Pandas data frame to make it easier to read and would like to have a column for read_id, and then columns for A, 6mA, 5mC, G, T. This is simple to do for mod_base_table but I'm struggling with how to do this for read_id.

Bottom line is, is there a correct way to do this with your package?

**Comment by JayVaz18** [comment]
> @JayVaz18,
> 
> Are you trying to use Python 3.9? There are packages available on PyPI for Python 3.5-3.8 inclusive. (The 3.7 and 3.8 ones have been added just today!)

I got fast5mod to install. However, when I simply run 'fast5mod' in the terminal to see if it worked, I get an error: "No module named 'libfast5mod'". Do you know why this is?

**Comment by cjw85** [comment]
Apologies for this, that's an interesting error. Can you try editing the file

    /Users/jakevazquez18/anaconda3/envs/py36/lib/python3.6/site-packages/fast5mod/executor.py

replacing `multiprocessing.queues.Queue` with `multiprocessing.Queue` and report what happens when you rerun the code?

**Comment by JayVaz18** [comment]
> /Users/jakevazquez18/anaconda3/envs/py36/lib/python3.6/site-packages/fast5mod/executor.py

No worries. This is the error I get after making that change: 

```
Traceback (most recent call last):
  File "/Users/jakevazquez18/anaconda3/envs/py36/bin/fast5mod", line 5, in <module>
    from fast5mod.fast5mod import main
  File "/Users/jakevazquez18/anaconda3/envs/py36/lib/python3.6/site-packages/fast5mod/fast5mod.py", line 7, in <module>
    import fast5mod.programs
  File "/Users/jakevazquez18/anaconda3/envs/py36/lib/python3.6/site-packages/fast5mod/programs.py", line 16, in <module>
    from fast5mod.executor import ProcessPoolExecutor, Queue, ThreadPoolExecutor
  File "/Users/jakevazquez18/anaconda3/envs/py36/lib/python3.6/site-packages/fast5mod/executor.py", line 74, in <module>
    class Queue(multiprocessing.Queue):
TypeError: method expected 2 arguments, got 3
```

**Comment by cjw85** [comment]
I believe this is a difference between Python 3.6 and Python 3.8 (which is where I tested this code). Can you create a conda environment with Python 3.8 and trying fast5mod in that?

**Comment by JayVaz18** [comment]
> I believe this is a difference between Python 3.6 and Python 3.8 (which is where I tested this code). Can you create a conda environment with Python 3.8 and trying fast5mod in that?

Interestingly, I get the error I was having before about 'libfast5mod':

```
Traceback (most recent call last):
  File "/Users/jakevazquez18/anaconda3/envs/py3.8.0/bin/fast5mod", line 5, in <module>
    from fast5mod.fast5mod import main
  File "/Users/jakevazquez18/anaconda3/envs/py3.8.0/lib/python3.8/site-packages/fast5mod/fast5mod.py", line 7, in <module>
    import fast5mod.programs
  File "/Users/jakevazquez18/anaconda3/envs/py3.8.0/lib/python3.8/site-packages/fast5mod/programs.py", line 17, in <module>
    import libfast5mod
ModuleNotFoundError: No module named 'libfast5mod'
```
But no error about the Queues

**Comment by cjw85** [comment]
I'm uncertain why your install reverted to showing that error if it was correctly downloading v1.0.4.

I believe I have fixed the multiprocessing Queue import errors in v1.0.5 which is now available on PyPI. I have tested this on my macOS machine, it appears to be working under both Python 3.6 and Python 3.8.

**Comment by JayVaz18** [comment]
> I'm uncertain why your install reverted to showing that error if it was correctly downloading v1.0.4.
> 
> I believe I have fixed the multiprocessing Queue import errors in v1.0.5 which is now available on PyPI. I have tested this on my macOS machine, it appears to be working under both Python 3.6 and Python 3.8.

Yes, I got it working on my end. Thank you SO much for your help. It is a great tool you have developed.

**Comment by JayVaz18** [comment]
> Hi @JayVaz18 -- so you're after something like this?
> 
> ```
> 0 <read_id> <A> <6mA> <C> <5mC> <G> <T>
> 1 <read_id> <A> <6mA> <C> <5mC> <G> <T>
> 2 <read_id> <A> <6mA> <C> <5mC> <G> <T>
> [...]
> ```
> 
> @cjw85 linked you some code to generate the full list of base names -- all you need to do then is finish the job:
> 
> ```
> import pandas as pd
> 
> df = pd.DataFrame(mod_base_table, columns=list_of_all_base_names)
> df['read_id'] = read_id
> ```

Well now I actually have this after running fast5mod --call.....

<img width="1106" alt="Screen Shot 2021-04-27 at 2 09 54 PM" src="https://user-images.githubusercontent.com/72083618/116291142-415a4280-a762-11eb-95e5-c7709a2e8691.png">

Which is great. However, I want to add a read_id column so for every position row, there will be a read_id value in the column next to it called "read". I realize there will be many repetitive values (reads) but it's necessary for us to see the reads along with the position

**Comment by JayVaz18** [comment]
@cjw85 is it possible to have the table that is output from fast5mod --call to include a column with read_ids?

**Comment by cjw85** [comment]
I presume you actually want two columns, one indicating reads with a modified base and one with an unmodified base? (There is actually a third class since some read sites are decided to be indeterminate).

You will have to make modifications to the code to achieve this. This could be done by modifying the `.add()` and `.summary()` methods of the `MotifTracker` class.

**Comment by JayVaz18** [comment]
> I presume you actually want two columns, one indicating reads with a modified base and one with an unmodified base? (There is actually a third class since some read sites are decided to be indeterminate).
> 
> You will have to make modifications to the code to achieve this. This could be done by modifying the `.add()` and `.summary()` methods of the `MotifTracker` class.

Ah, okay I see. I'm assuming I would use the reads variable from the hdf_to_sam_worker method that has the read_ids stored in it.

**Comment by cjw85** [comment]
I'm unclear what your ultimate goal is here. Going back to your original question, I presume that the table you asked how to construct is not your end goal.

It sounds like what you are after is knowing for given genomic loci, which reads contain modified bases and which do not. For that I would start by running the `fast5mod guppy2sam` program as demonstrated in the README to construct a BAM file which can be queried using the pysam pileup API. This is in essence what the `fast5mod call` program does ([pileup code](https://github.com/nanoporetech/fast5mod/blob/master/fast5mod/programs.py#L480)), albeit the program is complicated by performing this task efficiently over all genomic loci in a single pass.

**Comment by JayVaz18** [comment]
> I'm unclear what your ultimate goal is here. Going back to your original question, I presume that the table you asked how to construct is not your end goal.
> 
> It sounds like what you are after is knowing for given genomic loci, which reads contain modified bases and which do not. For that I would start by running the `fast5mod guppy2sam` program as demonstrated in the README to construct a BAM file which can be queried using the pysam pileup API. This is in essence what the `fast5mod call` program does ([pileup code](https://github.com/nanoporetech/fast5mod/blob/master/fast5mod/programs.py#L480)), albeit the program is complicated by performing this task efficiently over all genomic loci in a single pass.

Yes, that's essentially what I want to do. I would like to gather two views, one that shows the reads that are methylated and then within each read, the position in which the bases are methylated. I was looking at the pileup code yesterday and had a feeling I would have to do some work with that.
